### ISSUE TITLE
Flyway 4.x

### ISSUE THREAD

**Issue by ben-manes** [wstrzalka/gradle-flyway-jooq-plugin#1]
> Flyway.setInitOnMigrate() is deprecated. Use setBaselineOnMigrate() instead. Will be removed in Flyway 4.0.

I had [implemented](https://github.com/ben-manes/gradle-jooq-plugin/tree/master/example) this same feature back on the original flyway and jooq plugins, but happily handed those plugins off to others. I very much like this approach for codegen at compile time rather than checking it in.

It would be nice to remove the warning by updating your plugin to the latest versions.

**Comment by wstrzalka** [comment]
Updated

**Comment by ben-manes** [comment]
Thanks. Unfortunately it results in the failure,
```
> Failed to notify project evaluation listener.
   > pl/codelabs/flywayJooq/FlywayJooqInfoFileTask
...
Caused by: java.lang.IllegalAccessError: pl/codelabs/flywayJooq/FlywayJooqInfoFileTask
```

It appears to no longer be able to access the `AbstractFlywayTask`, which is why I didn't upgrade the flyway plugin directly. The class is abstract and package private, so perhaps later versions of Groovy honored that restriction.

**Comment by wstrzalka** [comment]
My bad that I didnt even tried it. Will take a look on it over the weekend hopefully

**Comment by ben-manes** [comment]
Thanks! Sorry I didn't think of anyone wanting to extend `AbstractFlywayTask` when I wrote it, so defaulted to hiding implementation details. Axel changed things since, but probably never thought about it either.

**Comment by wstrzalka** [comment]
This now waits for feedback from Axel [#1551](https://github.com/flyway/flyway/issues/1551)

**Comment by wstrzalka** [comment]
This shall be now fixed

**Comment by ben-manes** [comment]
Thanks again. I noticed you have a stale import in FlywayJooqInfoFileTask and I don't know if that would fail due to being in accessible.

**Comment by wstrzalka** [comment]
It's tested this time ;) 
I'd cleanup that up anyway and moved to use gradle logger.

Thanks for review
